[package]
name = "wufei"
version = "0.1.0"
authors = ["Eric McBride <ericmcbridedeveloper@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.31.2"
colored = "1.7"
rand = "0.6.5"
tokio-threadpool = "0.1.17"
futures = "0.1.19"
